### ISSUE TITLE
issue with pressing add layer to repo button

### ISSUE THREAD

**Issue by bartvde** [boundlessgeo/qgis-geogiglight-plugin#100]
Getting this error when clikcing on the add layer to repo button, @volaya says it should not let me press this button in this case:

![selection_017](https://cloud.githubusercontent.com/assets/319678/21927792/9a557eac-d987-11e6-88e6-329f6cde7d9f.png)

```
2017-01-13T11:54:38	1	Traceback (most recent call last):
			  File "/home/bartvde/.qgis2/python/plugins/geogig/gui/dialogs/navigatordialog.py", line 282, in addLayer
			    dlg = ImportDialog(self, repo = self.currentRepo)
			  File "/home/bartvde/.qgis2/python/plugins/geogig/gui/dialogs/importdialog.py", line 56, in __init__
			    self.initGui()
			  File "/home/bartvde/.qgis2/python/plugins/geogig/gui/dialogs/importdialog.py", line 84, in initGui
			    self.branches = self.repo.branches() if self.repo is not None else repos[0].branches()
			IndexError: list index out of range```

**Comment by gioman** [comment]
@volaya @bartvde I cannot replicate using the latest version available in the dev repository. When trying add a layer that is not a gpkg

![screenshot_20170117_135532](https://cloud.githubusercontent.com/assets/1951107/22023198/1b27aaa4-dcbd-11e6-9dda-7bd7c69ed471.png)

**Comment by bartvde** [comment]
yeah I probably ran into a corner case since the directory in geogig was deleted, though QGIS was restarted
