### ISSUE TITLE
python error on manual test "check export diff layer"

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#104]
Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/geogig/gui/dialogs/historyviewer.py", line 141, in 
    exportDiffAction.triggered.connect(lambda: self.exportDiffs(item.commit))
  File "/home/giovanni/.qgis2/python/plugins/geogig/gui/dialogs/historyviewer.py", line 246, in exportDiffs
    addDiffLayer(self.repo, tree, commit)
  File "/home/giovanni/.qgis2/python/plugins/geogig/tools/layers.py", line 229, in addDiffLayer
    beforeGpkgfid = gpkgfidFromGeogigfid(beforeCursor, layername, geogigfid)
  File "/home/giovanni/.qgis2/python/plugins/geogig/tools/layers.py", line 163, in gpkgfidFromGeogigfid
    gpkgfid = int(cursor.fetchone()[0])
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by gioman** [comment]
This seems long fixed now.
