### ISSUE TITLE
error in test "pull with conflicts"

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#105]
Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/geogig/gui/dialogs/navigatordialog.py", line 506, in pull
    conflicts = execute(lambda: self.currentRepo.pull(dlg.remote, dlg.branch))
  File "/home/giovanni/.qgis2/python/plugins/geogig/gui/executor.py", line 71, in execute
    return func()
  File "/home/giovanni/.qgis2/python/plugins/geogig/gui/dialogs/navigatordialog.py", line 506, in 
    conflicts = execute(lambda: self.currentRepo.pull(dlg.remote, dlg.branch))
  File "/home/giovanni/.qgis2/python/plugins/geogig/geogigwebapi/repository.py", line 653, in pull
    r.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:8182/repos/simple_1490282141.0/pull?transactionId=67276a99-1a57-47ca-9831-03bb35bd010e&ref=master&remoteName=myremote&output_format=json

**Comment by volaya** [comment]
It's an error on the server itself, there should be something in the geogig log describing what happened. CAn you post the geogig error trace?

**Comment by gioman** [comment]
@volaya should be this:

```
2017-03-24T15:05:57	0	GET: http://localhost:8182/repos/simple_1490367869.36/log
			PARAMS: {'countChanges': True, 'output_format': 'json', 'limit': 1, 'page': 0}
			RESPONSE: {u'response': {u'commit': [{u'committer': {u'timestamp': 1490367876955, u'name': u'me', u'timeZoneOffset': 0, u'email': u'me@mysite.com'}, u'adds': 0, u'author': {u'timestamp': 1490367876955, u'name': u'me', u'timeZoneOffset': 0, u'email': u'me@mysite.com'}, u'removes': 0, u'message': u'message', u'tree': u'da7023060fbe01729e9330bcb5cdf9f95282dd13', u'parents': {u'id': [u'1b714b86bd2168ada4ba119d6aea1d0fa4b3e2ea']}, u'modifies': 1, u'id': u'ce2d3a2e7d9ae05f0c99ab0c6008fc66e6d724d6'}], u'success': True}}
2017-03-24T15:05:57	0	GET: http://localhost:8182/repos/simple_1490367869.36/log
			PARAMS: {'countChanges': True, 'output_format': 'json', 'limit': 1, 'page': 1}
			RESPONSE: {u'response': {u'commit': [], u'success': True}}
2017-03-24T15:05:57	0	GET: http://localhost:8182/repos/simple_1490367869.36/ls-tree
			PARAMS: {'path': 'HEAD', 'output_format': 'json', 'onlyTrees': True}
			RESPONSE: {u'response': {u'node': [{u'path': u'points'}], u'success': True}}
2017-03-24T15:05:57	0	GET: http://localhost:8182/repos/simple_1490367869.36/ls-tree
			PARAMS: {'path': 'HEAD', 'output_format': 'json', 'onlyTrees': True}
			RESPONSE: {u'response': {u'node': [{u'path': u'points'}], u'success': True}}
2017-03-24T15:05:57	0	GET: http://localhost:8182/repos/simple_1490367869.36/branch
			PARAMS: {'output_format': 'json', 'list': True}
			RESPONSE: {u'response': {u'Remote': {u'Branch': []}, u'Local': {u'Branch': [{u'name': u'master'}, {u'name': u'mybranch'}]}, u'success': True}}
2017-03-24T15:05:58	0	GET: http://localhost:8182/repos/simple_1490367869.36/remote
			PARAMS: {'output_format': 'json', 'list': True, 'verbose': True}
			RESPONSE: {u'response': {u'Remote': [{u'url': u'http://localhost:8182/repos/simple_1490367864.68/', u'name': u'myremote'}], u'success': True}}
2017-03-24T15:05:58	0	GET: http://localhost:8182/repos/simple_1490367869.36/branch
			PARAMS: {'output_format': 'json', 'list': True}
			RESPONSE: {u'response': {u'Remote': {u'Branch': []}, u'Local': {u'Branch': [{u'name': u'master'}, {u'name': u'mybranch'}]}, u'success': True}}
2017-03-24T15:06:00	0	GET: http://localhost:8182/repos/simple_1490367869.36/beginTransaction?output_format=json
			PARAMS: {'output_format': 'json'}
			RESPONSE: {u'response': {u'Transaction': {u'ID': u'fe16342d-004c-4eff-83f2-a370c4a2eb6f'}, u'success': True}}
2017-03-24T15:06:00	0	GET: http://localhost:8182/repos/simple_1490367869.36/checkout?transactionId=fe16342d-004c-4eff-83f2-a370c4a2eb6f&branch=master
			PARAMS: {'transactionId': u'fe16342d-004c-4eff-83f2-a370c4a2eb6f', 'branch': u'master'}
			RESPONSE: <?xml version="1.0" ?><response><success>true</success><OldTarget>refs/heads/master</OldTarget><NewTarget>master</NewTarget></response>
```

**Comment by gioman** [comment]
Fix confirmed.
