### ISSUE TITLE
error in test "sync with conflict with remove and modify" when solving with "modify"

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#106]
Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/geogig/tools/gpkgsync.py", line 120, in syncLayer
    conflict.resolveWithLocalVersion()
  File "/home/giovanni/.qgis2/python/plugins/geogig/geogigwebapi/diff.py", line 87, in resolveWithLocalVersion
    self.repo.resolveConflictWithFeatureId(self.path, self.localFeatureId, self.transactionId)
  File "/home/giovanni/.qgis2/python/plugins/geogig/geogigwebapi/repository.py", line 506, in resolveConflictWithFeatureId
    r.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:8182/repos/simple_1490283509.76/resolveconflict?path=points%2Ffid-b94414_15afaf4ffff_-7d08&transactionId=6eb9c9cd-48fa-4771-ac1c-18f7680c3eb0&objectid=0000000000000000000000000000000000000000

**Comment by gioman** [comment]
Confirmed working.
