### ISSUE TITLE
error in test "merge with conflicts in several layers"

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#107]
Test name: GeoGig Light-Merge with conflicts in several layers
Test result:Test failed at step 'Create merge conflict' with message:
400 Client Error: Bad Request for url: http://localhost:8182/repos/severallayers_1490283745.19/checkout?transactionId=112d380a-a2c4-4a08-994b-c0c5fbb8b03d&branch=mybranch
Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/qgistester/testerwidget.py", line 142, in runNextStep
    execute(step.function)
  File "/home/giovanni/.qgis2/python/plugins/qgistester/utils.py", line 70, in execute
    return func()
  File "/home/giovanni/.qgis2/python/plugins/geogig/tests/testplugin.py", line 236, in _createMergeConflictInSeveralLayers
    _createMergeScenario("points")
  File "/home/giovanni/.qgis2/python/plugins/geogig/tests/testplugin.py", line 219, in _createMergeScenario
    tests._lastRepo.importgeopkg(layer, "mybranch", "changed_%s_1" % layername, "me", "me@mysite.com", True)
  File "/home/giovanni/.qgis2/python/plugins/geogig/geogigwebapi/repository.py", line 403, in importgeopkg
    self._checkoutbranch(branch, transactionId)
  File "/home/giovanni/.qgis2/python/plugins/geogig/geogigwebapi/repository.py", line 311, in _checkoutbranch
    r.raise_for_status()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 400 Client Error: Bad Request for url: http://localhost:8182/repos/severallayers_1490283745.19/checkout?transactionId=112d380a-a2c4-4a08-994b-c0c5fbb8b03d&branch=mybranch

**Comment by gioman** [comment]
Confirmed working.
