### ISSUE TITLE
python error in test "change layer version"

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#108]
it actually happens after the change of version is done (and works) and "next step" is clicked:

Traceback (most recent call last):
  File "/home/giovanni/.qgis2/python/plugins/qgistester/testerwidget.py", line 119, in runNextStep
    execute(step.function)
  File "/home/giovanni/.qgis2/python/plugins/qgistester/utils.py", line 70, in execute
    return func()
  File "/home/giovanni/.qgis2/python/plugins/geogig/tests/testplugin.py", line 407, in <lambda>
    test.addStep("Check context menu info", lambda: _checkContextMenuInfo("third"))
  File "/home/giovanni/.qgis2/python/plugins/geogig/tests/testplugin.py", line 297, in _checkContextMenuInfo
    assert text in actions[0].text().lower()
AssertionError

**Comment by gioman** [comment]
Fixed or no more replicable.
