### ISSUE TITLE
python error on QGIS exit

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#27]
Frequently when exiting QGIS a python error from geogig plugin is thrown, even when during session no Geogig related work/operations were made:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 388, in unloadPlugin
    plugins[packageName].unload()
  File "/home/giovanni/.qgis2/python/plugins/geogig/plugin.py", line 96, in unload
    sys.excepthook = self.qgisHook
AttributeError: GeoGigPlugin instance has no attribute 'qgisHook'
```

**Comment by gioman** [comment]
Seen also after upgrading the plugin on Linux.

**Comment by gioman** [comment]
And now also seen

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 388, in unloadPlugin
    plugins[packageName].unload()
  File "/home/giovanni/.qgis2/python/plugins/geogig/plugin.py", line 92, in unload
    QgsMapLayerRegistry.instance().layerWasAdded.disconnect(trackLayer)
TypeError: 'function' object is not connected
```

on exit (and again on Linux, so not an officially supported platform).

**Comment by gioman** [comment]
Seen on update also on Windows:

```
Traceback (most recent call last):
  File "C:/PROGRA~1/BOUNDL~1/Desktop/osgeo4w/apps/qgis/./python\qgis\utils.py", line 361, in unloadPlugin
    plugins[packageName].unload()
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\plugin.py", line 96, in unload
    sys.excepthook = self.qgisHook
AttributeError: GeoGigPlugin instance has no attribute 'qgisHook'
```

**Comment by volaya** [comment]
should be fixed now, I removed the wrong line that was causing the error. Can you confirm?

**Comment by gioman** [comment]
Not seeing the python errors anymore after the upgrade to the latest code, so the fix is confirmed.
