### ISSUE TITLE
feature info tool: error + internal server error

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#31]
Started with a fresh repo.

Added a layer, made an edit (added polygon) and commited with "sync layer with repository branch".

Changed to initial version with "change to a different version".

Made another edit (added another polygon) and tried to user the two tools in "feature info tool" on the newly added feature:

"Show all versions of this feature" returns

`The feature id (com/315) cannot be found in the repository`

"com" is the layer name, curiously the number "315" never changes.

"Show authorship" causes an Internal Server error in Geogig server

An error has occurred while executing Python code: 

```
HTTPError: 500 Server Error: Internal Server Error for url: http://193.136.217.133:8182/repos/repos/blame?path=com%2F315&output_format=json 
Traceback (most recent call last):
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\tools\infotool.py", line 84, in 
    blameAction.triggered.connect(lambda: self.blame(repo, trackedlayer.layername, fid))
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\tools\infotool.py", line 101, in blame
    dlg = BlameDialog(repo, path)
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\dialogs\blamedialog.py", line 33, in __init__
    self.blamedata = repo.blame(path)
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\geogigwebapi\repository.py", line 273, in blame
    resp = self._apicall("blame", {"path":path})
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\geogigwebapi\repository.py", line 147, in _apicall
    return execute(lambda: self.__apicall(command, payload, transaction))
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\executor.py", line 69, in execute
    return func()
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\geogigwebapi\repository.py", line 147, in 
    return execute(lambda: self.__apicall(command, payload, transaction))
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\geogigwebapi\repository.py", line 137, in __apicall
    r.raise_for_status()
  File "C:\Users\qgis\.qgis2\python\plugins\geogig\ext-libs\requests-2.9.1-py2.7.egg\requests\models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://193.136.217.133:8182/repos/repos/blame?path=com%2F315&output_format=json


```

**Comment by volaya** [comment]
I fied the error with blame. I also changed the wording in the other case

It is actuallynot a bug. You are trying to see the versions of a feature that is new, that means, it is not versioned yet, so there are no versions. Until you sync and put the feature in the repo, there is no info about it and about its versions.

**Comment by gioman** [comment]
> It is actuallynot a bug. You are trying to see the versions of a feature that is new, that means, it is not versioned yet, so there are no versions. Until you sync and put the feature in the repo, there is no info about it and about its versions.

yes of course, that was just me trying to do anything a final users could do :)
the new message in the dialog is clear now.

Unfortunately after that when try to commit the new version I started having serious "database is locked" issues. Seeing now if finally I can replicate in a precise way.

**Comment by gioman** [comment]
> Seeing now if finally I can replicate in a precise way.

unfortunately I still can't.
