### ISSUE TITLE
python error in "merge conflicts" dialog after deleting a feature

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#52]
- choose a specific version

- delete a feature, in a way that you know that the changes will cause a conflict

- open the "merge conflicts" dialog

- when choosing the conflict to resolve:

```
Traceback (most recent call last):
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\dialogs\conflictdialog.py", line 163, in treeItemClicked
    self.updateCurrentPath()
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\dialogs\conflictdialog.py", line 169, in updateCurrentPath
    self.showFeatureAttributes()
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\dialogs\conflictdialog.py", line 271, in showFeatureAttributes
    values = (conflictItem.origin[name], conflictItem.local[name], conflictItem.remote[name])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by volaya** [comment]
This is a known limitation, the case where a feature has been both modified and deleted... I will work on that

**Comment by gioman** [comment]
Fix confirmed.
