### ISSUE TITLE
python error in comparison view + version list not populated

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#63]
```
Traceback (most recent call last):
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\dialogs\diffviewerdialog.py", line 96, in treeItemChanged
    self.treeItemClicked(current)
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\dialogs\diffviewerdialog.py", line 99, in treeItemClicked
    if item.childCount():
AttributeError: 'NoneType' object has no attribute 'childCount'
```

it seems that something broke in one of the latest changes.

When opening the comparison view, when clicking the button to choose a specific version to be used for the comparison, only the "branch" dropdown is populated and clicking ok causes the error.

**Comment by gioman** [comment]
@alexbruy it does not seems fixed here: in a repo with just one layer no more python error, but when trying a specific version to be used for comparison the dropdown is empty (now the tag dropdown is populated).

In a repo with >1 layer I see strange things, not sure if is a regression, More on that soon.

**Comment by gioman** [comment]
> In a repo with >1 layer I see strange things, not sure if is a regression, More on that soon.

same as in a repo with 1 layer (no versions listed). I thought I was seeing something strange but I can't see it again now.

**Comment by gioman** [comment]
> I thought I was seeing something strange but I can't see it again now.

ok, I'm able now to replicate a different python error when in a repo I have two layers, each one with a couple of versions. In this specific moment I'm using tags to change versions in comparison viewer because the version dropdown is not populated (see above).

```
Traceback (most recent call last):
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\dialogs\diffviewerdialog.py", line 103, in treeItemChanged
    parent = current.parent().parent()
AttributeError: 'NoneType' object has no attribute 'parent'
```

So I have a point layer and a polygon layer, in comparison view for "old" I choose the first version of the polygon layer, in "new" I choose the branch (master). This creates the situation in the image below, where the point layer and its changed are listed. For the polygon layer just the name is shown, and clicking on it causes the python error.

![screenshot from 2016-07-29 16-55-17](https://cloud.githubusercontent.com/assets/1951107/17254608/61169c38-55ad-11e6-889f-0d30ae7714f1.png)

**Comment by gioman** [comment]
Fix confirmed.
