### ISSUE TITLE
python error when server unreacheable

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#65]
On few occasions (but not always) when for some reasons the server is unreacheable I got python errors like the following ones. Is a minor issue but it could be worth as improvement to catch them and return a dialog instead

```
GeoGigException: Network connection error
HTTPConnectionPool(host='193.136.217.163', port=8182): Max retries exceeded with url: /repos/repos/branch?output_format=json&list=True (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))
```

```
GeoGigException: Network connection error
HTTPConnectionPool(host='193.136.217.238', port=8182): Max retries exceeded with url: /repos/repos/tag?output_format=json (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10051] A socket operation was attempted to an unreachable network',))

Traceback (most recent call last):
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\dialogs\historyviewer.py", line 110, in _itemExpanded
    item.populate()
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\dialogs\historyviewer.py", line 202, in populate
    for k, v in self.repo.tags().iteritems():
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\geogigwebapi\repository.py", line 160, in tags
    r = self._apicall("tag", {})
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\geogigwebapi\repository.py", line 147, in _apicall
    return execute(lambda: self.__apicall(command, payload, transaction))
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\executor.py", line 69, in execute
    return func()
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\geogigwebapi\repository.py", line 147, in
    return execute(lambda: self.__apicall(command, payload, transaction))
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\geogigwebapi\repository.py", line 144, in __apicall
    raise GeoGigException(msg)
GeoGigException: Network connection error
HTTPConnectionPool(host='193.136.217.238', port=8182): Max retries exceeded with url: /repos/repos/tag?output_format=json (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 10051] A socket operation was attempted to an unreachable network',))
```

**Comment by gioman** [comment]
cannot see this anymore, will reopen if necessary.
