### ISSUE TITLE
python error when examining modified geometries in "comparison view"

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#66]
When clicking the new button "view detail" (using the latest code revision).

```
Traceback (most recent call last):
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\dialogs\diffviewerdialog.py", line 143, in 
    btn.clicked.connect(lambda: self.viewGeometryChanges(qgsgeom1, qgsgeom2))
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\dialogs\diffviewerdialog.py", line 160, in viewGeometryChanges
    dlg = GeometryDiffViewerDialog([g1, g2], QgsCoordinateReferenceSystem("EPSG:4326")) #TODO set CRS correctly
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\dialogs\geometrydiffviewerdialog.py", line 49, in __init__
    self.initGui()
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\dialogs\geometrydiffviewerdialog.py", line 69, in initGui
    execute(self.createLayers)
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\executor.py", line 69, in execute
    return func()
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\dialogs\geometrydiffviewerdialog.py", line 86, in createLayers
    text = geom.exportToWkt()
AttributeError: 'NoneType' object has no attribute 'exportToWkt'
```

**Comment by volaya** [comment]
Not able to reproduce. Any additional info about how the feature has been modified and the geometry type? Or better if you can provide a repo in which this can be reproduced

**Comment by gioman** [comment]
@volaya Updated to latest code revision and still get it. Attached the repository witht layer/version causing the issue. Load "gp_poli" the in history examine changes introduced by version "poli_third" (the change was modifying and existing polygon feature).

[repos3.tar.gz](https://github.com/boundlessgeo/qgis-geogiglight-plugin/files/393473/repos3.tar.gz)

**Comment by gioman** [comment]
Fix confirmed.
