### ISSUE TITLE
python error in "merge conflicts" when choosing a base layer

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#68]
either openstreetmap or google maps

```
Traceback (most recent call last):
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\plugin.py", line 54, in trackLayer
    setAsNonRepoLayer(layer)
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\layeractions.py", line 136, in setAsNonRepoLayer
    action.setEnabled(layer.storageType() == 'GPKG')
AttributeError: 'QgsRasterLayer' object has no attribute 'storageType
```

**Comment by gioman** [comment]
fix confirmed.
