### ISSUE TITLE
Error when adding layer to QGIS

### ISSUE THREAD

**Issue by elpaso** [boundlessgeo/qgis-geogiglight-plugin#7]
Steps to reproduce:
- create a local repo as described in the tutorial http://geogig.org/docs/data/import.html
- import data from a shapefile
- add the repo in QGIS 

Repo summary:
TITLE: repo1 
URL: http://localhost:8182/repos/repo1/ 
LAST VERSION: First import (lug 11, 2016 05:28 by elpaso) 
LAYERS [Add all layers to QGIS]: 
points2 [Add to QGIS] 

- click on [Add to QGIS]
- the error below appears in a dialog
- the layer is added to QGIS but it's empty

```
Plugin version: 1.0
Traceback (most recent call last):
  File "/home/ale/.qgis2/python/plugins/geogig/plugin.py", line 55, in trackLayer
    setAsRepoLayer(layer)
  File "/home/ale/.qgis2/python/plugins/geogig/layeractions.py", line 51, in setAsRepoLayer
    commitId = getCommitId(layer)
  File "/home/ale/.qgis2/python/plugins/geogig/tools/gpkgsync.py", line 204, in getCommitId
    cursor.execute("SELECT commit_id FROM geogig_audited_tables WHERE table_name='%s';" % layername)
OperationalError: no such column: commit_id
```

QGIS info:

Versione di QGIS
2.14.3-Essen
QGIS code branch
Release 2.14
Compilato con Qt
4.8.7
Esecuzione con Qt
4.8.7
Compilato con GDAL/OGR
1.11.3
Esecuzione con GDAL/OGR
1.11.3
Compilato con GEOS
3.5.0-CAPI-1.9.0
Esecuzione con GEOS
3.5.0-CAPI-1.9.0 r4084
Versione client PostgreSQL
9.5.2
Versione SpatiaLite
4.3.0a
Versione QWT
5.2.3
Versione PROJ.4
492
Versione QScintilla2
2.9.1

**Comment by elpaso** [comment]
More information: in the gpkg file the `commit_id` field is missing.

```
geogig.sh --version
         Project Version : 1.0-RC2
              Build Time : April 07, 2016 at 14:53:12 ART
         Build User Name : Gabriel Roldan
        Build User Email : groldan@boundlessgeo.com
              Git Branch : r1.0-RC2
           Git Commit ID : 65854cd741d3c5c2f9248e57034d4a3fa6831927
         Git Commit Time : April 07, 2016 at 13:29:07 ART
  Git Commit Author Name : Gabriel Roldan
 Git Commit Author Email : groldan@boundlessgeo.com
      Git Commit Message : Set version to 1.0-RC2

Signed-off-by: Gabriel Roldan <groldan@boundlessgeo.com>
```

**Comment by elpaso** [comment]
Updated to latest dev (RC3) and error went away after speaking to @groldan
