### ISSUE TITLE
python error in "merge conflicts" when clicking on "solve with..."

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#70]
the error is always the same, regardless choosing "local", "remote" or "merged".

```
AttributeError: 'Repository' object has no attribute 'closeConflictSolving' 
Traceback (most recent call last):
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\layeractions.py", line 129, in _syncLayer
    if syncLayer(layer):
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\tools\gpkgsync.py", line 110, in syncLayer
    repo.closeConflictSolving(user, email, "Resolved merge conflicts", conflicts[0].transactionId)
AttributeError: 'Repository' object has no attribute 'closeConflictSolving
```

**Comment by gioman** [comment]
Fix confirmed.
