### ISSUE TITLE
Pyhton error when removing layer from repository tree

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#79]
```
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:8182/repos/29_simple/commit?authorEmail=ggg%40ggg.com&all=True&transactionId=b6fa6262-6ab1-4309-a608-b87603c8ef31&message=removed+layer+points&authorName=ggg 
Traceback (most recent call last):
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\dialogs\navigatordialog.py", line 305, in deleteCurrentElement
    self._removeLayer(item.layer)
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\gui\dialogs\navigatordialog.py", line 186, in _removeLayer
    self.currentRepo.removetree(layername, user, email)
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\geogigwebapi\repository.py", line 302, in removetree
    self.commitAndCloseTransaction(user, email, "removed layer %s" % path, transactionId)
  File "C:/Users/qgis/.qgis2/python/plugins\geogig\geogigwebapi\repository.py", line 453, in commitAndCloseTransaction
    r.raise_for_status()
  File "C:\Users\qgis\.qgis2\python\plugins\geogig\ext-libs\requests-2.9.1-py2.7.egg\requests\models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:8182/repos/29_simple/commit?authorEmail=ggg%40ggg.com&all=True&transactionId=b6fa6262-6ab1-4309-a608-b87603c8ef31&message=removed+layer+points&authorName=ggg
```

I'm on BD Desktop 1.0 on Windows 7 with the latest plugin code.

**Comment by gioman** [comment]
fixed with https://github.com/boundlessgeo/qgis-geogiglight-plugin/commit/c3470a0972ad590aa3629285e495a9faf534cc3d
