### ISSUE TITLE
Python error when syncing after deleting a lot of features

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-geogiglight-plugin#88]
Traceback (most recent call last):
 File "C:/Users/boundless/.qgis2/python/plugins\geogig\gui\dialogs\historyviewer.py", line 122, in
   exportDiffAction.triggered.connect(lambda: self.exportDiffs(item.commit))
 File "C:/Users/boundless/.qgis2/python/plugins\geogig\gui\dialogs\historyviewer.py", line 228, in exportDiffs
   addDiffLayer(self.repo, tree, commit)
 File "C:/Users/boundless/.qgis2/python/plugins\geogig\tools\layers.py", line 217, in addDiffLayer
   beforeGpkgfid = gpkgfidFromGeogigfid(beforeCursor, layername, geogigfid)
 File "C:/Users/boundless/.qgis2/python/plugins\geogig\tools\layers.py", line 152, in gpkgfidFromGeogigfid
   gpkgfid = int(cursor.fetchone()[0])
TypeError: 'NoneType' object has no attribute '**getitem**'

**Comment by gioman** [comment]
@volaya after the latest changes in the plugin and BL Desktop I cannot replicate this anymore (this is using GG server RC3 as we have in the testing Docker container). Will re-open if necessary.
