### ISSUE TITLE
Operational error DB is locked after sync

### ISSUE THREAD

**Issue by elpaso** [boundlessgeo/qgis-geogiglight-plugin#95]
Dev version of the plugin + dev version of GeoGig with OSM and BDB plugins enabled.

After moving one feature:
- sync
- select GeoGig feature info tool
- click on the moved feature

```
2016-12-20T13:32:13	1	Traceback (most recent call last):
			  File "/home/xxx/.qgis2/python/plugins/geogig/tools/gpkgsync.py", line 129, in syncLayer
			    updateFeatureIds(repo, layer, featureIds)
			  File "/home/xxx/.qgis2/python/plugins/geogig/tools/gpkgsync.py", line 169, in updateFeatureIds
			    con.commit()
			OperationalError: database is locked
```

Last Logged call:
```
2016-12-20T13:32:08	0	GET: http://localhost:38080/repos/repo1/endTransaction?transactionId=d5f8ecdc-86a8-427d-877e-ae29476fd399
			PARAMS: {'transactionId': u'd5f8ecdc-86a8-427d-877e-ae29476fd399'}
			RESPONSE: <?xml version='1.0' encoding='UTF-8'?><response><success>true</success><Transaction><ID>d5f8ecdc-86a8-427d-877e-ae29476fd399</ID></Transaction></response>
```

**Comment by gioman** [comment]
@volaya @elpaso I cannot confirm here, I'm using a version of GG server that volaya provided me recently to test the latest changes in the plugin.

**Comment by volaya** [comment]
That error is not in the server, but on the QGIS side. Is the one that is supposed to have been fixed by Even. @elpaso, which QGIS version are you using?

**Comment by elpaso** [comment]
latest 2.18.2 on ubuntu

**Comment by gioman** [comment]
@elpaso what is the status of this issue? I cannot replicate with GG light master, GG 1.0 and qgis 2.18.4 on Ubuntu 16.04
