### ISSUE TITLE
plugin fails to start: ImportError "builtins"

### ISSUE THREAD

**Issue by sebastian-r-schmidt** [boundlessgeo/qgis-geogiglight-plugin#96]
Hi,
after builiding this plugin on a linux host, I transferred the zipfile to a windows 7 Machine using QGIS 2.14.0 There the plugin does not start giving the following stacktrace:

```
2016-12-23T12:47:14	1	Traceback (most recent call last):
			  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python\qgis\utils.py", line 306, in startPlugin
			    plugins[packageName] = package.classFactory(iface)
			  File "C:/Users/Schmidt.Sebastian2/.qgis2/python/plugins\geogig\__init__.py", line 33, in classFactory
			    from geogig.plugin import GeoGigPlugin
			  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			  File "C:/Users/Schmidt.Sebastian2/.qgis2/python/plugins\geogig\plugin.py", line 18, in <module>
			    from builtins import object
			  File "C:/PROGRA~1/QGISES~1/apps/qgis/./python\qgis\utils.py", line 572, in _import
			    mod = _builtin_import(name, globals, locals, fromlist, level)
			ImportError: No module named builtins
```

Is the "future" package for python 3/2 compatibility missing in the 2.14 series?

**Comment by gioman** [comment]
@sebastian-r-schmidt yes, python-future is not a dependency in qgis 2.*. As a workaround you can install it using pip using the osgeo console that is available in any QGIS/BL Desktop installation.

**Comment by sebastian-r-schmidt** [comment]
Hi, thanks for the fast reply. Will try to install it on the 2.14. series.
In QGIS 2.16.0 the "Future" package seems to be included in the QGIS windows build.

**Comment by gioman** [comment]
@sebastian-r-schmidt python-future will be a dependency in next qgis/bl desktop builds.
